-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "bank_dealer",
    [2] = "Duffel Bag"
}

game:GetService("ReplicatedStorage")._network.purchase:InvokeServer(unpack(args))
