-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "gun_store",
    [2] = "Ruger LCP"
}

game:GetService("ReplicatedStorage")._network.purchase:InvokeServer(unpack(args))
